modified Install your load balancer

diff --git a/0x0F-load_balancer/1-install_load_balancer b/0x0F-load_balancer/1-install_load_balancer
--- a/0x0F-load_balancer/1-install_load_balancer
+++ b/0x0F-load_balancer/1-install_load_balancer
@@ -1,67 +1,76 @@
 #!/usr/bin/env bash
-set -e
-
 # This script installs and configures the HAproxy load balancer. It configures
-# the server to send traffic to two web servers. The load balanceing algorithm
+# the server to send traffic to two web servers. The load balancing algorithm
 # is round-robin.
+
+# Define variables
+DOMAIN_NAME='phinehas.tech'
+WEB_SERVER_1='54.172.89.45'
+WEB_SERVER_2='100.25.144.184'
+FRONTEND_NAME='phine_frontend'
+BACKEND_NAME='phine_backend'
+
+# HAProxy configuration
 config="
-frontend phine_frontend
+frontend $FRONTEND_NAME
     bind *:80
     mode http
-    default_backend phine_backend
+    default_backend $BACKEND_NAME
     timeout client 30s
     timeout connect 30s
     timeout server 30s
 
-backend phine_backend
+backend $BACKEND_NAME
     balance roundrobin
-    server 87098-web-01- web-01.phinehas.tech:80 check
-    server 87098-web-02 web-02.phinehas.tech:80 check
+    server $DOMAIN_NAME-web-01 $WEB_SERVER_1:80 check
+    server $DOMAIN_NAME-web-02 $WEB_SERVER_2:80 check
     timeout server 30s
     timeout connect 30s
 "
 
+# Check if the user is root
 if [ $EUID -ne 0 ]; then
     echo "You must be root to run this script."
     exit 1
 fi
 
+# Function to add configuration to HAProxy
 function add_config() {
-    # let's do some house checking first, ensure the configuration does not 
-    # exist before we append to it
-    if ! grep -q -e "phine_frontend" -e "phine_backend" /etc/haproxy/haproxy.cfg; then
-        # configure HAproxy
-        echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
-    else
+    # Check if configuration already exists
+    if grep -q -e "$FRONTEND_NAME" -e "$BACKEND_NAME" /etc/haproxy/haproxy.cfg; then
         echo "Configuration already exists."
-        exit
+        exit 1
     fi
 
+    # Add configuration to HAProxy
+    echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
+
+    # Enable HAProxy if not already enabled
     if ! grep -q "ENABLED" /etc/default/haproxy; then
         echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null
     fi
 
-    # restart HAproxy
+    # Check HAProxy configuration syntax
+    if ! sudo haproxy -c -f /etc/haproxy/haproxy.cfg; then
+        echo "HAProxy configuration syntax check failed."
+        exit 1
+    fi
+
+    # Restart HAProxy
     sudo systemctl restart haproxy
 }
 
-# let's save time and check if the HAproxy package is already installed
+# Check if HAProxy is installed
 if ! command -v haproxy > /dev/null; then
-    # update package list
+    # Update package list
     sudo apt-get update -y
 
-    # enable dedicated PPA for HAproxy 2.8
-    if ! command -v add-apt-repository > /dev/null; then
-        sudo apt-get install --no-install-recommends -y software-properties-common
-    fi
-
-    sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
-
-    # install HAproxy
+    # Install HAProxy
     sudo apt-get install -y haproxy
 
+    # Add configuration
     add_config
 else
-    # HAproxy is already installed, just add the configuration
+    # Add configuration
     add_config
 fi
